"""add provider model prompt and policy version to pipeline results

Revision ID: 43464ca90094
Revises: 7686cb73582d
Create Date: 2026-09-27 18:05:35.135607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43464ca90094'
down_revision: Union[str, Sequence[str], None] = '7686cb73582d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_results', sa.Column('provider', sa.String(length=50), nullable=True))
    op.add_column('pipeline_results', sa.Column('model_name', sa.String(length=100), nullable=True))
    op.add_column('pipeline_results', sa.Column('prompt_version', sa.String(length=20), nullable=True))
    op.add_column('pipeline_results', sa.Column('policy_version', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_results', 'policy_version')
    op.drop_column('pipeline_results', 'prompt_version')
    op.drop_column('pipeline_results', 'model_name')
    op.drop_column('pipeline_results', 'provider')
    # ### end Alembic commands ###
