"""add verification score to pipeline comparisons

Revision ID: 4c9be3e2b8d0
Revises: 836c9535efb3
Create Date: 2026-09-27 23:44:38.126055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c9be3e2b8d0'
down_revision: Union[str, Sequence[str], None] = '836c9535efb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_comparisons', sa.Column('verification_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_comparisons', 'verification_score')
    # ### end Alembic commands ###
