"""add knowledge base chunks table

Revision ID: 5bd7221b005b
Revises: 772616192cca
Create Date: 2026-09-27 22:45:14.341091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bd7221b005b'
down_revision: Union[str, Sequence[str], None] = '772616192cca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_base_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=20), nullable=True),
    sa.Column('heading', sa.String(length=255), nullable=True),
    sa.Column('page_reference', sa.Integer(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_base_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_chunks_document_id'), 'knowledge_base_chunks', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_base_chunks_document_id'), table_name='knowledge_base_chunks')
    op.drop_table('knowledge_base_chunks')
    # ### end Alembic commands ###
