"""initial schema

Revision ID: 6d08d9286fa7
Revises: 
Create Date: 2026-09-26 14:53:06.643302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d08d9286fa7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('departments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('escalation_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.String(length=20), nullable=False),
    sa.Column('trigger_condition', sa.Text(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('level_name', sa.String(length=100), nullable=False),
    sa.Column('response_time', sa.String(length=50), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalation_rules_level'), 'escalation_rules', ['level'], unique=False)
    op.create_index(op.f('ix_escalation_rules_rule_id'), 'escalation_rules', ['rule_id'], unique=True)
    op.create_table('knowledge_base_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_documents_document_id'), 'knowledge_base_documents', ['document_id'], unique=True)
    op.create_table('resolution_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('subcategory', sa.String(length=255), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('urgency', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('policy_id', sa.String(length=20), nullable=True),
    sa.Column('escalation_required', sa.Boolean(), nullable=False),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('required_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prohibited_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('follow_up', sa.String(length=255), nullable=True),
    sa.Column('compensation_eligible', sa.Boolean(), nullable=False),
    sa.Column('refund_eligible', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resolution_rules_category'), 'resolution_rules', ['category'], unique=False)
    op.create_index(op.f('ix_resolution_rules_rule_id'), 'resolution_rules', ['rule_id'], unique=True)
    op.create_index(op.f('ix_resolution_rules_subcategory'), 'resolution_rules', ['subcategory'], unique=False)
    op.create_table('subcategories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_subcategories_category_id'), 'subcategories', ['category_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('CUSTOMER', 'AGENT', 'REVIEWER', 'MANAGER', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('loyalty_tier', sa.Enum('SILVER', 'GOLD', 'PLATINUM', name='loyalty_tier'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_department_id'), 'users', ['department_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('complaints',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('complaint_id', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('channel', sa.Enum('WEB_FORM', 'CHAT', 'EMAIL', 'DOCUMENT', name='complaint_channel'), nullable=False),
    sa.Column('product_type', sa.String(length=50), nullable=False),
    sa.Column('booking_reference', sa.String(length=20), nullable=True),
    sa.Column('customer_selected_category', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('SUBMITTED', 'VALIDATING', 'PROCESSING', 'UNDER_REVIEW', 'ASSIGNED', 'IN_PROGRESS', 'AWAITING_CUSTOMER', 'RESOLVED', 'CLOSED', 'REOPENED', 'ESCALATED', name='complaint_status'), nullable=False),
    sa.Column('priority', sa.Enum('P0', 'P1', 'P2', 'P3', name='priority'), nullable=True),
    sa.Column('urgency', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='urgency'), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('subcategory_id', sa.Uuid(), nullable=True),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_agent_id', sa.Uuid(), nullable=True),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('escalation_reason', sa.Text(), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('duplicate_of', sa.Uuid(), nullable=True),
    sa.Column('is_prompt_injection', sa.Boolean(), nullable=False),
    sa.Column('has_conflict', sa.Boolean(), nullable=False),
    sa.Column('conflict_resolved_by', sa.Uuid(), nullable=True),
    sa.Column('conflict_resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_response_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_resolution_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_response_met', sa.Boolean(), nullable=True),
    sa.Column('sla_resolution_met', sa.Boolean(), nullable=True),
    sa.Column('satisfaction_rating', sa.Integer(), nullable=True),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['conflict_resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['duplicate_of'], ['complaints.id'], ),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaints_booking_reference'), 'complaints', ['booking_reference'], unique=False)
    op.create_index(op.f('ix_complaints_complaint_id'), 'complaints', ['complaint_id'], unique=True)
    op.create_index(op.f('ix_complaints_customer_id'), 'complaints', ['customer_id'], unique=False)
    op.create_index(op.f('ix_complaints_department_id'), 'complaints', ['department_id'], unique=False)
    op.create_index(op.f('ix_complaints_priority'), 'complaints', ['priority'], unique=False)
    op.create_index(op.f('ix_complaints_status'), 'complaints', ['status'], unique=False)
    op.create_table('complaint_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Enum('CREATED', 'STATUS_CHANGED', 'PRIORITY_CHANGED', 'ASSIGNED', 'ESCALATED', 'NOTE_ADDED', 'RESPONSE_SENT', 'CONFLICT_RESOLVED', 'REOPENED', 'CLOSED', name='history_action'), nullable=False),
    sa.Column('performed_by', sa.Uuid(), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaint_history_complaint_id'), 'complaint_history', ['complaint_id'], unique=False)
    op.create_index(op.f('ix_complaint_history_created_at'), 'complaint_history', ['created_at'], unique=False)
    op.create_table('customer_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('sender', sa.Enum('CUSTOMER', 'AGENT', 'SYSTEM', name='message_sender'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_messages_complaint_id'), 'customer_messages', ['complaint_id'], unique=False)
    op.create_table('pipeline_comparisons',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('has_conflict', sa.Boolean(), nullable=False),
    sa.Column('conflict_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('conflict_severity', sa.Enum('NONE', 'MINOR', 'MAJOR', 'CRITICAL', name='conflict_severity'), nullable=False),
    sa.Column('genai_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ground_truth_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('final_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reviewer_id', sa.Uuid(), nullable=True),
    sa.Column('reviewer_rationale', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_comparisons_complaint_id'), 'pipeline_comparisons', ['complaint_id'], unique=True)
    op.create_table('pipeline_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('pipeline', sa.Enum('GENAI', 'GROUND_TRUTH', name='pipeline_type'), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('subcategory', sa.String(length=255), nullable=True),
    sa.Column('sentiment', sa.String(length=50), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('urgency', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='pr_urgency'), nullable=True),
    sa.Column('priority', sa.Enum('P0', 'P1', 'P2', 'P3', name='pr_priority'), nullable=True),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('escalation_required', sa.Boolean(), nullable=False),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('refund_eligible', sa.Boolean(), nullable=False),
    sa.Column('compensation_eligible', sa.Boolean(), nullable=False),
    sa.Column('matched_rule_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('matched_escalation_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('policy_references', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('required_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prohibited_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('suggested_response', sa.Text(), nullable=True),
    sa.Column('resolution_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('entities_extracted', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('raw_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_results_complaint_id'), 'pipeline_results', ['complaint_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_results_complaint_id'), table_name='pipeline_results')
    op.drop_table('pipeline_results')
    op.drop_index(op.f('ix_pipeline_comparisons_complaint_id'), table_name='pipeline_comparisons')
    op.drop_table('pipeline_comparisons')
    op.drop_index(op.f('ix_customer_messages_complaint_id'), table_name='customer_messages')
    op.drop_table('customer_messages')
    op.drop_index(op.f('ix_complaint_history_created_at'), table_name='complaint_history')
    op.drop_index(op.f('ix_complaint_history_complaint_id'), table_name='complaint_history')
    op.drop_table('complaint_history')
    op.drop_index(op.f('ix_complaints_status'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_priority'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_department_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_customer_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_complaint_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_booking_reference'), table_name='complaints')
    op.drop_table('complaints')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_department_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subcategories_category_id'), table_name='subcategories')
    op.drop_table('subcategories')
    op.drop_index(op.f('ix_resolution_rules_subcategory'), table_name='resolution_rules')
    op.drop_index(op.f('ix_resolution_rules_rule_id'), table_name='resolution_rules')
    op.drop_index(op.f('ix_resolution_rules_category'), table_name='resolution_rules')
    op.drop_table('resolution_rules')
    op.drop_index(op.f('ix_knowledge_base_documents_document_id'), table_name='knowledge_base_documents')
    op.drop_table('knowledge_base_documents')
    op.drop_index(op.f('ix_escalation_rules_rule_id'), table_name='escalation_rules')
    op.drop_index(op.f('ix_escalation_rules_level'), table_name='escalation_rules')
    op.drop_table('escalation_rules')
    op.drop_table('departments')
    op.drop_table('categories')
    # ### end Alembic commands ###
