"""add supporting department to complaints

Revision ID: 7686cb73582d
Revises: 81d81e396db7
Create Date: 2026-09-27 18:03:52.946650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7686cb73582d'
down_revision: Union[str, Sequence[str], None] = '81d81e396db7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('supporting_department_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(
        'fk_complaints_supporting_department_id_departments',
        'complaints', 'departments', ['supporting_department_id'], ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_complaints_supporting_department_id_departments', 'complaints', type_='foreignkey')
    op.drop_column('complaints', 'supporting_department_id')
    # ### end Alembic commands ###
