"""add primary and secondary issue to pipeline results

Revision ID: 81d81e396db7
Revises: b83a83b9cefe
Create Date: 2026-09-27 17:49:55.726184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81d81e396db7'
down_revision: Union[str, Sequence[str], None] = 'b83a83b9cefe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_results', sa.Column('primary_issue', sa.String(length=255), nullable=True))
    op.add_column('pipeline_results', sa.Column('secondary_issue', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_results', 'secondary_issue')
    op.drop_column('pipeline_results', 'primary_issue')
    # ### end Alembic commands ###
