"""add review reason to complaints

Revision ID: 836c9535efb3
Revises: 5468a457b0ec
Create Date: 2026-09-27 23:19:08.300130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '836c9535efb3'
down_revision: Union[str, Sequence[str], None] = '5468a457b0ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('review_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'review_reason')
    # ### end Alembic commands ###
