"""expand resolution rule and escalation rule schema

Revision ID: 93ce0bae89d7
Revises: f652be9348e5
Create Date: 2026-09-26 15:42:44.493200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93ce0bae89d7'
down_revision: Union[str, Sequence[str], None] = 'f652be9348e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('escalation_rules', sa.Column('relative_level', sa.String(length=50), nullable=True))
    op.add_column('escalation_rules', sa.Column('priority_override', sa.String(length=10), nullable=True))
    op.alter_column('escalation_rules', 'level',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('escalation_rules', 'level_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.add_column('resolution_rules', sa.Column('supporting_department', sa.String(length=50), nullable=True))
    op.add_column('resolution_rules', sa.Column('follow_up_days', sa.Integer(), nullable=True))
    # resolution_rules is unpopulated at this point in development, so a plain
    # drop/recreate is simpler and safer than a VARCHAR->Boolean USING cast.
    op.drop_column('resolution_rules', 'follow_up')
    op.add_column('resolution_rules', sa.Column('follow_up', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('resolution_rules', 'follow_up', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resolution_rules', 'follow_up')
    op.add_column('resolution_rules', sa.Column('follow_up', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('resolution_rules', 'follow_up_days')
    op.drop_column('resolution_rules', 'supporting_department')
    op.alter_column('escalation_rules', 'level_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('escalation_rules', 'level',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('escalation_rules', 'priority_override')
    op.drop_column('escalation_rules', 'relative_level')
    # ### end Alembic commands ###
