"""add next_follow_up_at to complaints

Revision ID: a56efdde4de3
Revises: 3b900ee9d0bd
Create Date: 2026-09-28 11:46:28.103991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a56efdde4de3'
down_revision: Union[str, Sequence[str], None] = '3b900ee9d0bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('next_follow_up_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'next_follow_up_at')
    # ### end Alembic commands ###
