"""add email intake log table

Revision ID: b69b4cd1b109
Revises: e5ccc08b3c80
Create Date: 2026-09-28 15:05:25.253012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b69b4cd1b109'
down_revision: Union[str, Sequence[str], None] = 'e5ccc08b3c80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_intake_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.String(length=998), nullable=False),
    sa.Column('from_address', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=998), nullable=False),
    sa.Column('outcome', sa.Enum('COMPLAINT_CREATED', 'ATTACHED_TO_EXISTING', 'UNCLASSIFIED', 'MANUAL_REVIEW_UNVERIFIED_SENDER', 'MANUAL_REVIEW_UNREGISTERED_SENDER', name='email_intake_outcome'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('complaint_id', sa.Uuid(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_intake_logs_message_id'), 'email_intake_logs', ['message_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_intake_logs_message_id'), table_name='email_intake_logs')
    op.drop_table('email_intake_logs')
    # ### end Alembic commands ###
