"""make complaint_history.performed_by nullable for system actions

Revision ID: b83a83b9cefe
Revises: 93ce0bae89d7
Create Date: 2026-09-26 20:05:35.372151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b83a83b9cefe'
down_revision: Union[str, Sequence[str], None] = '93ce0bae89d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('complaint_history', 'performed_by',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('complaint_history', 'performed_by',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
