"""add expiry_date to knowledge_base_documents

Revision ID: ba77e6de7eab
Revises: c4479f4e30e0
Create Date: 2026-09-28 11:06:44.084003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba77e6de7eab'
down_revision: Union[str, Sequence[str], None] = 'c4479f4e30e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_base_documents', sa.Column('expiry_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_base_documents', 'expiry_date')
    # ### end Alembic commands ###
