"""add clarification questions to pipeline results

Revision ID: c4479f4e30e0
Revises: 4c9be3e2b8d0
Create Date: 2026-09-28 04:07:47.290298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4479f4e30e0'
down_revision: Union[str, Sequence[str], None] = '4c9be3e2b8d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_results', sa.Column('clarification_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_results', 'clarification_questions')
    # ### end Alembic commands ###
