"""add validation_issues to pipeline results

Revision ID: e5ccc08b3c80
Revises: b65c894a7053
Create Date: 2026-09-28 12:27:36.668839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5ccc08b3c80'
down_revision: Union[str, Sequence[str], None] = 'b65c894a7053'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_results', sa.Column('validation_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_results', 'validation_issues')
    # ### end Alembic commands ###
